### ISSUE TITLE
Create pg client inside plugin?

### ISSUE THREAD

**Issue by SimonLab** [postgres-plugin/tags-system#4]
Is it ok to create a new pg client inside the plugin? Is it better to pass the client in the options of the plugin to avoid creating a new connection?

**Comment by mk4111** [comment]
@SimonLab I think it would be good to pool the client too - could we use [dwyl's hapi-postgres-connection](https://github.com/dwyl/hapi-postgres-connection) for this?

**Comment by JMurphyWeb** [comment]
If a client is passed, use it, if no client is passed we need to create one.

For version 0.0.0001 maybe we can assume that a client will be passed via the options?

**Comment by JMurphyWeb** [comment]
@SimonLab @mk4111 I guess we never really established what we would do with this.

For now I have created the client inside the plugin. I am currently working on exposing a closeClient function so we can close the connection and our tests don't hang.

**Comment by mk4111** [comment]
@JMurphyWeb - How are you writing the test? Is it similar to the issue that we had, which we resolved by using .onFinish in all our tests? Simon looked at the issue with me, and we found that the tests were hanging because (at the top of each test file,) we require in server.js, which has server.start in it; every time we used a server method (e.g. server.inject), that meant that we were invoking server.start!

**Comment by JMurphyWeb** [comment]
@mk4111 that is what we were doing in our project too. I have created issue on the hanging tests: https://github.com/SimonLab/tags-system/issues/25

**Comment by mk4111** [comment]
@JMurphyWeb I'm quite sure we had to put server.stop() inside of .onFinish to stop our tests from hanging...

**Comment by JMurphyWeb** [comment]
We did, but i think we had that to close the connection to redis.

We have a start.js file in our project.

**Comment by mk4111** [comment]
Hmm I'm sure we just had that to close the server at the very end; thought closing the connection to redis was client.end()...

Yeah we had one to begin with, then we were requested to put it into server.js, and then we extracted it back out because of the issue of duplicate copies of mockdata being put into the database... I think we bumped into the issue of the tests hanging when we put start.js into server.js and our fix at the time was to close everything(client and server) in .onFinish

**Comment by JMurphyWeb** [comment]
Yeap. So we had the starting of the server in a different file to begin with to prevent this exact issue happening.

**Comment by mk4111** [comment]
Sorry I'm only just catching up with the issues! In that case, we've got server.stop() in every test (in the emf repo) for no reason, so we'll need to keep a mental note to remove it :D

**Comment by SimonLab** [comment]
We create a pool outside the plugin (in the application) and pass this pool to the plugin. This allow the plugin to get some connections to postgres without creating a new pool
