### ISSUE TITLE
Get by tag function

### ISSUE THREAD

**Issue by JMurphyWeb** [postgres-plugin/tags-system#52]
getByTag(tableName, tagId, cb)

**Comment by JMurphyWeb** [comment]
I am not too sure about making this function re-usable for all tables.

Mainly because we need to decide which columns we want, and what to rename those columns to, which will be different for challenges and organisations.

Here is an example that is specific for challenges.

```js
module.exports = function getChallengesByTag (tagId) {
  return `SELECT
      tags.id, tags.name,
      challenges.id, challenges.date, challenges.title, challenges.description,
      challenges.creator_id, challenges.creator_id
    from tags
    JOIN
      tags_challenges ON tags.id = ` + tagId + ` AND tags_challenges.tags_id = tags.id
    JOIN
    challenges ON tags_challenges.challenges_id = challenges.id;` //eslint-disable-line
}
```

**Comment by SimonLab** [comment]
I think we can pass as a parameter the name of the columns we want to retrieve. This will allow to keep just one more abstract function instead of creating multiple similar functions getChanllengesByTag, getOrganisationByTag. For example could we have this kind of structure for the more abstract function:

```
module.exports = function getByTag (tableName, columns, tagId, cb) {
  return `SELECT
      tags.id, tags.name,` +
      tableNane + `.id, ` + columns.join(',') +
    `from tags
    JOIN
  ...
}

```

Then we can call the function like this:

```
getByTag ('challenges', ['date', 'title', 'description', 'creator_id], tagId, function (err, resp) {...})
```

Will this work? Otherwise I think we will have to add each functions (getChallengesByTags, getOrganistaionByTags,...) in their own plugin as I don't think these kind of functions belong to the tags plugin.

**Comment by JMurphyWeb** [comment]
I think calling these functions each time will get a little tedious. Alternatively we could just return all columns and prefix each one with `challenges_`

But I think I am happy to move this function into challenges if that is preferable.

**Comment by JMurphyWeb** [comment]
I think i would be happy to go with your first suggestion, I can see that we would only need to define the array of columns once inside the plugin, so that should be fine.

**Comment by JMurphyWeb** [comment]
closed with https://github.com/postgres-plugin/challenges/issues/9
